databases:
  - name: islamic-school-db
    databaseName: school_management
    user: school_admin
    plan: free

services:
  - type: web
    name: islamic-school-management
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: islamic-school-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: APP_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: dhqih0txj
      - key: CLOUDINARY_API_KEY
        value: "768711335699391"
      - key: CLOUDINARY_API_SECRET
        value: Trvy26meoa_1XQ70qTsCrFWGq2w
